# ManhuntGG Configuration
# Plugin version: 1.0.0

# Game Duration Settings (in seconds)
durations:
  lobby: 60            # Duration of the lobby phase
  preparation: 30      # Grace period before hunters are released
  border-shrink: 1200  # Time until border reaches final size (20 minutes)
  ending: 10          # Duration of end-game phase

# World Border Configuration
border:
  initial-size: 4000.0  # Starting border diameter in blocks
  final-size: 100.0     # Final border diameter after shrinking
  warning-distance: 25  # Distance at which players get border warnings
  warning-time: 15      # Time before damage when near border

# Player Management
players:
  min-players: 2       # Minimum players required to start
  max-players: 10      # Maximum players allowed in game
  hunter-spawn-radius: 500.0  # Initial distance hunters spawn from runner
  hunter-respawn-radius: 100.0  # Distance hunters respawn from runner after death

# Combat Settings
combat:
  friendly-fire: false  # Whether hunters can damage each other
  runner-health-broadcasts: true  # Broadcast runner health when damaged

# World Settings
worlds:
  lobby:
    name: "manhunt_lobby"
    type: "FLAT"
    generate-structures: false
    environment: "NORMAL"
  game:
    name: "manhunt_world"
    type: "NORMAL"
    generate-structures: true
    environment: "NORMAL"

# Game Rules
game-rules:
  do-immediate-respawn: true
  announce-advancements: false
  do-insomnia: false
  do-daylight-cycle: true
  do-weather-cycle: true

# Debug Settings
debug:
  enabled: false
  log-level: "INFO"  # Valid: INFO, WARNING, SEVERE