name: Manhuntgg
version: '${version}'
main: co.sakurastudios.manhuntgg.Manhuntgg
api-version: '1.21'
author: SakuraStudios
description: A manhunt plugin for your server!
depend: [TAB]
commands:
  manhunt:
    description: Main command for Manhunt
    usage: /manhunt <start|stop>
    permission: manhunt.admin
  shout:
    description: Broadcast a message to all players
    usage: /shout <message>
    permission: manhunt.shout
permissions:
  manhunt.admin:
    description: Allows control of manhunt games
    default: op
  manhunt.shout:
    description: Allows using the shout command
    default: true